version: "3.8"

services:
  app:
    build:
      args:
        uid: ${DOCKER_APP_UID}
        user: ${DOCKER_APP_USER}
      context: ./
      dockerfile: ./docker/app/Dockerfile
    container_name: notes_api-app
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - 5173:5173
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - notes_api

  db:
    image: mysql:8.0.30
    restart: unless-stopped
    container_name: notes_api-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - notes_api-db:/var/lib/mysql
    networks:
      - notes_api

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    container_name: notes_api-phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - notes_api

  nginx:
    image: nginx:1.22.1-alpine
    container_name: notes_api-nginx
    restart: unless-stopped
    ports:
      - ${SERVER_PORT}:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - notes_api
 
volumes:
  notes_api-db:

networks:
  notes_api:
    driver: bridge

